services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12

  mailpit:
    image: axllent/mailpit:v1.27
    ports:
      - "1025:1025"
      - "8025:8025"

  prometheus:
    image: prom/prometheus:v3.5.0
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"
    volumes:
      - ./observability-service/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:12.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./observability-service/grafana:/etc/grafana/provisioning:ro
