global:
  scrape_interval: 5s

rule_files:
  - prometheus-alerts.yml

scrape_configs:
  - job_name: observability-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:8081
  - job_name: order-service
    scheme: https
    metrics_path: /metrics/business
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - order-service.test:443
